### ISSUE TITLE
Unable to run with latest master

### ISSUE THREAD

**Issue by vityafx** [etaoins/llambda#59]
I have just downloaded `master` branch and I can't run `llambda`:

```
[fx@purplejam llambda]$ ./llambda test.scm
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /data/data/workspace/llambda/project
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Set current project to llambda (in build file:/data/data/workspace/llambda/)
[warn] The `-` command is deprecated in favor of `onFailure` and will be removed in 0.14.0
[info] Set current project to compiler (in build file:/data/data/workspace/llambda/)
[info] Defining compiler/*:showSuccess
[info] The new value will be used by no settings or tasks.
[info] Reapplying settings...
[info] Set current project to compiler (in build file:/data/data/workspace/llambda/)
[info] Packaging /data/data/workspace/llambda/compiler/target/scala-2.12/compiler_2.12-0.0.1.jar ...
[info] Done packaging.
[info] Running io.llambda.compiler.CompilerApp test.scm
[debug] Waiting for threads to exit or System.exit to be called.
[debug]   Classpath:
[debug] 	/tmp/sbt_1a86b402/job-1/target/0b411cc6/compiler_2.12-0.0.1.jar
[debug] 	/tmp/sbt_1a86b402/target/8412a978/llvmir_2.12-0.0.1.jar
[debug] 	/tmp/sbt_1a86b402/target/f2e496f2/scala-library.jar
[debug] 	/tmp/sbt_1a86b402/target/e078455e/scopt_2.12-3.7.0.jar
[debug] 	/tmp/sbt_1a86b402/target/5d040d73/jline-2.14.4.jar
[debug] 	/tmp/sbt_1a86b402/target/f8b74a59/parboiled_2.12-2.1.4.jar
[debug] 	/tmp/sbt_1a86b402/target/27e115ff/shapeless_2.12-2.3.2.jar
[debug] 	/tmp/sbt_1a86b402/target/ed809d26/macro-compat_2.12-1.1.1.jar
[debug] Waiting for thread run-main-0 to terminate.
[error] (run-main-0) java.lang.NullPointerException
[error] java.lang.NullPointerException
[error] 	at io.llambda.compiler.CompilerApp$.$anonfun$new$11(CompilerApp.scala:116)
[error] 	at io.llambda.compiler.CompilerApp$.$anonfun$new$11$adapted(CompilerApp.scala:73)
[error] 	at scala.Option.map(Option.scala:146)
[error] 	at io.llambda.compiler.CompilerApp$.delayedEndpoint$io$llambda$compiler$CompilerApp$1(CompilerApp.scala:73)
[error] 	at io.llambda.compiler.CompilerApp$delayedInit$body.apply(CompilerApp.scala:6)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.App.main(App.scala:76)
[error] 	at scala.App.main$(App.scala:74)
[error] 	at io.llambda.compiler.CompilerApp$.main(CompilerApp.scala:6)
[error] 	at io.llambda.compiler.CompilerApp.main(CompilerApp.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:89)
[error] 	at sbt.Run.run0(Run.scala:83)
[error] 	at sbt.Run.execute$1(Run.scala:61)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:73)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at sbt.Run$.executeTrapExit(Run.scala:120)
[error] 	at sbt.Run.run(Run.scala:73)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$5(Defaults.scala:1152)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$5$adapted(Defaults.scala:1147)
[error] 	at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:359)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:282)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (compiler/compile:run) Nonzero exit code: 1
```

Tried on archlinux (latest), ubuntu 16.04 and the mac os x (latest), the same thing everywhere.

**Comment by BartMassey** [comment]
Me too. It's some  CMake thing, I think.

**Comment by BartMassey** [comment]
Thanks much! I'll give it a try.

**Comment by BartMassey** [comment]
Nope.

```
bartfan @ sbt
[info] Loading project definition from /usr/local/src/llambda/project
[info] Set current project to llambda (in build file:/usr/local/src/llambda/)
> project compiler
[info] Set current project to compiler (in build file:/usr/local/src/llambda/)
> run /home/bart/test.scm
[info] Running io.llambda.compiler.CompilerApp /home/bart/test.scm
[error] (Thread-8) java.io.IOException: Cannot run program "llc": error=2, No such file or directory
java.io.IOException: Cannot run program "llc": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
	at scala.sys.process.ProcessImpl$PipedProcesses.runAndExitValue(ProcessImpl.scala:138)
	at scala.sys.process.ProcessImpl$PipedProcesses.runAndExitValue(ProcessImpl.scala:117)
	at scala.sys.process.ProcessImpl$CompoundProcess.$anonfun$x$4$1(ProcessImpl.scala:96)
	at scala.sys.process.ProcessImpl$Spawn$$anon$1.run(ProcessImpl.scala:23)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
	at scala.sys.process.ProcessImpl$PipedProcesses.runAndExitValue(ProcessImpl.scala:138)
	at scala.sys.process.ProcessImpl$PipedProcesses.runAndExitValue(ProcessImpl.scala:117)
	at scala.sys.process.ProcessImpl$CompoundProcess.$anonfun$x$4$1(ProcessImpl.scala:96)
	at scala.sys.process.ProcessImpl$Spawn$$anon$1.run(ProcessImpl.scala:23)
[trace] Stack trace suppressed: run last compiler/compile:run for the full output.
```

**Comment by etaoins** [comment]
@BartMassey Looks like `llc` isn't in your path? Is LLVM installed?

**Comment by BartMassey** [comment]
Doh. I'm dumb: hadn't realized what `llc` is. LLVM is installed, but on Debian all the binary names are suffixed with the version. I wrote a fancy `update-alternatives` script and got `llc` pointing to `llc-3.6` in my path. On to the next issue. Thanks.
